KebabCase: 케밥 케이스를 추가합니다. 케밥케이스 -> 매크로케이스
fastcampus/fastcase pull request #14
Opened 2020-10-06 00:19 UTC by akiraei

케밥케이스를 매크로케이스로 변경하는 함수를 추가합니다

![image](https://user-images.githubusercontent.com/37572753/95145006-0b994080-07b5-11eb-9d09-3988fbcb3513.png)

2020-10-06 00:42 UTC, iolo approved these changes
LGTM!

2020-10-06 00:45 UTC, iolo commented on src/index.ts
> + * convert the given **kebab_case** string to a macroCase string,
코멘트는 케이스 스타일의 샘플입니다.
`**kebab-case** **MACRO_CASE**`

2020-10-06 00:46 UTC, iolo requested changes
index.ts의 toMacroCase, toMacroCaseFast, toMacroCaseKeys는 필요없습니다.
지금 index.ts의 toCamelCase, toCamelCaseKeys...는 하위호환성을 위해 남겨둔것입니다.

2020-10-06 00:48 UTC, iolo reviewed
Q. camel <-> snake 사이의 변환은 흔히 있는 일인데...
kebab -> macro 사이의 변환은 언제 사용하는 건가요?

2020-10-06 00:50 UTC, akiraei commented
> Q. camel <-> snake 사이의 변환은 흔히 있는 일인데...
> kebab -> macro 사이의 변환은 언제 사용하는 건가요?

저희 admin의 url에서 query 변수를 추출할 때, 변수가 policy와 관련될 때 사용하려고 합니다.
policy의 키 값이 macro 케이스인데 url은 기본이 kebab이라고 생각되어서 생성하게 됐습니다

2020-11-02 06:14 UTC, iolo commented
이게 최초 버전에서는 snake-case <-> camelCase 만 생각하고 시작한거라...
toSnakeCase는 camelCaseToSnakeCase,
toCamelCase는 snakeCaseToCamelCase... 라고 인정했던건데...

새로운 case가 추가되면 toMacroCase 만으로는 kekabCaseToMacroCase 라고 하기 힘들죠.
snakeCaseToMacroCase가 될 수도 있으니까요.

그렇다면
```js
import { toMacroCase } from '@fastcampus/fastcase/kebab-case';
```
처럼 쓰라고 해야할지...

아니면, 기존과 유사하게
kekabToMacro (or kebabCaseToMacroCase) 같은 편의함수를 따로 만들어주는게 좋을지...
의견 좀 주세요. /cc @soomtong

2020-11-03 02:10 UTC, soomtong commented
상식적인 캐밥/스네이크 스타일이 (추후 다른 타입도) 매크로 타입으로 변경되는 것을 스펙이라 가정하고 현재 API 함수 이름을 유지하면 어떨까 싶습니다.

가능하면 현재의 단순함, 즉, toXXX 만으로 사용하는 패턴을 유지하는게 우선된다고 생각했습니다.

2021-03-14 07:10 UTC, plainOldCode commented
이 PR 도 5개월이 넘었는데 어떻게 병합되거나 닫혀야 하지 않을까 합니다.

2021-03-22 06:49 UTC, akiraei commented
> 이 PR 도 5개월이 넘었는데 어떻게 병합되거나 닫혀야 하지 않을까 합니다.

전부터 닫았어야 했는데 죄송합니다
닫는 이유는
- fastcase는 snake/kebab만을 위해서 (일단) 작동한다
- 다른 케이스가 필요한 경우는 따로 정리한다
입니다

2021-03-22 06:49 UTC, closed without merging